name: Deploy Node.js project to Azure Function App

on:
  push:
    branches: ["master"]

env:
  AZURE_FUNCTIONAPP_NAME: 'your-app-name'           # 🔁 Replace with your Azure Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './quantum-nexus'      # 🔁 Replace if your function app is in a different folder
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install, Build, and Test
      shell: pwsh
      run: |
        pushd "./${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
        npm install
        npm run build --if-present
        npm run test --if-present
        popd

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
